## config.py

# Model Configurations

DATA_PATH = './data/Train.csv'
SEED = 777
MAX_SEQ_LEN = 64
VOCAB_SIZE = 4477
EMBEDDING_DIM = 64
LSTM_UNITS = 32
DENSE_UNITS = 16
DROP_OUT_RATE = 0.5
EPOCHS = 4
BATCH_SIZE = 8

# Tweepy Configurations
CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""
